### ISSUE TITLE
New version numbering scheme?

### ISSUE THREAD

**Issue by kastl-ars** [deggja/netfetch#204]
Dear deggja,

I see you changed the version numbers in the releases recently. Will those stay on 0.x.y?

I packaged netfetch (the CLI) for openSUSE, which currently has 5.2.10. Packaging the new ones means I need to manage a downgrade for users having the package installed...

Kind Regards,
Johannes

**Comment by deggja** [comment]
Hello @kastl-ars!
Yes, the versioning scheme was recently changed, however the change from 5.1.0 -> 0.5.3 was purely cosmetic. There are no breaking changes and a change to the new version is completely safe.

The versioning was changed due to a not so well implemented version bumping script/github action that needed fixing, but never really found the time to do so.

**Comment by kastl-ars** [comment]
Thanks for the fast reply. So the versioning will continue with 0.x.y permanently?

At first I was wondering if the new scheme was for e.g. a helm chart while the 5.x.y was for the CLI or similar...

**Comment by deggja** [comment]
Yes, the scheme will not change from here on out, unless necessary when updating the application. Versioning will be [semantic](https://semver.org/), so any breaking changes will result in a new major version and so on.

I should probably have added something about this in the release notes, my bad.

**Comment by kastl-ars** [comment]
Thanks for the fast clarification!
